.travis.yml, tasks/setup-Debian.yml
=> Fix adding docker apt key on Ubuntu 14.04

README.md, defaults/main.yml
I bumped it on my machine and it passed the tests. Figured it would be good to have this in the official repository.
Thanks for all your contributions @geerlingguy!
=> Bump docker_compose_version to 1.16.1.

README.md, defaults/main.yml
See https://github.com/docker/compose/releases/tag/1.21.2
=> Update docker-compose version to 1.21.2

tasks/docker-users.yml
=> Update user's supplementary group membership, not primary group

tasks/setup-RedHat.yml
Bumps containerd version from 1.2.6-3.3 to 1.2.13-3.2.
=> Bump containerd version

tasks/setup-RedHat.yml
Main idea is to disable container-tools module with dnf
=> containerd install fix for rhel8

README.md, defaults/main.yml, tasks/setup-RedHat.yml
=> Fixes #239: Switch from 'Edge' to 'Nightly' option since Edge is not a thing now.

tasks/main.yml
=> Add check and ignore installation errors in `--check` mode

.github/workflows/ci.yml, meta/main.yml
=> Add Debian 11

tasks/docker-compose.yml
```
yaml: truthy value should be one of [false, true] (truthy)
roles/geerlingguy.docker/tasks/docker-compose.yml:5
```
Fixes geerlingguy/ansible-role-docker#325
=> style: fix ansible-lint nit about truthy value

tasks/docker-compose.yml
Attempt to fix issue described in #338
=> Update conditional for docker-compose check

tasks/docker-compose.yml
=> Fix docker-compose update

tasks/setup-Debian.yml
=> Download apt key directly

tasks/docker-compose.yml
=> Fix condition for empty docker compose svn

vars/Alpine.yml, vars/Archlinux.yml
Variable name in override files did not match the variable name set in defaults/main.yml therefore it did not take effect.
This PR fixes it.
```
TASK [geerlingguy.docker : Load OS-specific vars.] ****************************************************************************************************************************************************************
task path: /builds/foobar/playbooks/roles/geerlingguy.docker/tasks/main.yml:2
Thursday 10 November 2022  21:03:49 +0000 (0:00:00.054)       0:00:02.312 *****
Thursday 10 November 2022  21:03:49 +0000 (0:00:00.054)       0:00:02.309 *****
ok: [localhost] => {
"ansible_facts": {
"docker_package": "docker"
},
"ansible_included_var_files": [
"/builds/foobar/playbooks/roles/geerlingguy.docker/vars/Alpine.yml"
],
"changed": false
}
TASK …
```
=> Make override work by adjusting variable name to match defaults/main.yml

defaults/main.yml
=> debian: add signed-by param to the apt source list

README.md
May want to also add a task to check for one of the old filenames and modify the variable if it's present. Lmk and I can either add it here or submit a separate PR
=> Update documentation on docker_apt_filename

README.md
Fix typo in Yum repos definition
=> Fix a README typo in Yum variables

tasks/setup-Debian.yml
Matches https://docs.docker.com/engine/install/debian/#uninstall-old-versions
=> Update list of obsolete pkgs

.github/workflows/ci.yml
Adds latest Ubuntu LTS to CI pipeline
=> Add Ubuntu 24.04 to CI

tasks/main.yml
Reverts geerlingguy/ansible-role-docker#498
=> Revert "Ensure the Docker daemon options file (`/etc/docker/daemon.json`) is deleted when no longer needed"

README.md, defaults/main.yml
=> Specify RedHat-specific repo
