tasks/setup-RedHat.yml
Cron builds seem to start failing as of this morning, possibly due to the `container-selinux` removal on CentOS 7.
=> Fix broken idempotence.

README.md
The problem with the syntax highlighting was that you used both indentation and triple backticks. This removes the indentation.
=> fixes yaml syntax highlighting in README

defaults/main.yml, tasks/main.yml
By default var will be `present` to do not break legacy.
Fixes #14
=> Add var to customize docker pkg state

README.md, defaults/main.yml
Nice module and thanks for making it available!
Could you please consider this PR to add armhf package support to the default configuration? I know I can override the repository URL in my playbook, but it would be nice for it to "just work" for both amd64 and armhf architectures. By removing this bit apt should fall back on the value in the apt configuration.
There are also s390x packages for Xenial:
https://download.docker.com/linux/ubuntu/dists/xenial/stable/
I presume this would add support for that architecture too, though do not have access to such a system to test.
=> Open up support for armhf architecture

tasks/main.yml
The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
=> 'include' for tasks has been deprecated

defaults/main.yml, tasks/setup-Debian.yml
Just ignoring an error regarding the Docker GPG key and downloading it
from "some" web page is not desired in any environment.
=> Make ignoring repository key error optional

README.md, defaults/main.yml, tasks/main.yml
According to the docs (https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository#set-up-the-repository), Docker needs the CPU architecture to be specified in the apt source definition under Debian/Ubuntu.
Otherwise updating the sources fails with „N: Skipping acquire of configured file 'stable/binary-i386/Packages' as repository 'https://download.docker.com/linux/ubuntu xenial InRelease' doesn't support architecture 'i386‘“
Although the correct package has been installed!
This PR introduces an additional config param for Debian/Ubuntu to setting the CPU architecture to either amd64 or i386.
=> Debian apt amd64

tasks/setup-Debian.yml
Fixes these warnings by heeding the advice.
```
TASK [geerlingguy.docker : Ensure curl is present (on older systems without SNI).] *************************************************
Friday 11 May 2018  09:08:15 -0400 (0:00:02.128)       0:02:28.194 ************ 
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|failed` instead use `result is failed`. This 
feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
TASK [geerlingguy.docker : Add Docker apt key (alternative for older systems without SNI).] ****************************************
Friday 11 May 2018  09:08:15 -0400 (0:00:00.067)       0:02:28.261 ************ 
[DEPRECATION WARNING]: Using tests as filters is deprecated. …
```
=> Fix 'using tests as filters' deprecation warning

tasks/main.yml
Fix for the following 2 deprecation warnings under Ansible 2.8:
```sh
[DEPRECATION WARNING]: evaluating docker_install_compose as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This feature will be removed in version 2.12. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: evaluating docker_users as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This feature will be removed in version 2.12. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```
=> Fixes deprecation warnings about evaluating bare variables

README.md, defaults/main.yml
Changed docker compose version to the latest release 1.26.0: https://github.com/docker/compose/releases
Closes #208
=> Change default docker compose version to 1.26.0

tasks/setup-RedHat.yml
=> Fixes #243: Remove step that disables container-tools on CentOS 8.

defaults/main.yml, tasks/docker-compose.yml
These changes are needed for the role to be usable in an offline environment where github.com and docker.com are inaccessible, or if a user desires to use a local mirror. It allows for configuration of the docker-compose download URL, as well as setting a YUM and APT package mirror. Finally, docker-compose is only downloaded when needed.
=> Add ability to configure package mirrors

tasks/setup-Debian.yml
This pull request is about adding a condition to not install `gnupg2` on Ubuntu 20.04 and superior since this package is no more.
=> Do not install gnupg2 on Ubuntu 20.04 and superior

handlers/main.yml, tasks/main.yml
When running playbook using this role for the first time, and in `--check` mode, some things are pretty much guaranteed to fail.  Rather than stop processing, would be nice if we could continue with the rest of the playbook and see what else is likely to change or fail.
I suppose one could be a bit more deliberate about it if you wanted the results/output to be cleaner, but that would require checking if the package is actually installed. 
LMK if you prefer that approach and I'll rework.
=> ignore likely errors if in `ansible_check_mode`

README.md, defaults/main.yml, tasks/main.yml
Based on #92
Fixes #90
Fixes #84
As @geerlingguy commented on #92, do not touch the configuration file if no configuration provided.
Also move configuration before starting docker, to avoid starting docker unconfigured (and possibly failing) and then restart with correct configuration
=> Ability to configure Docker daemon options

tasks/setup-Debian.yml
The sudo dependency should not be needed because sudo escalation is
managed by Ansible.
=> Remove sudo dependency

tasks/main.yml
Dear @adamantike,
thank you very much for your report at #346:
> Root cause is #336, as the introduced parameter `allow_downgrade` is not supported by the `pacman` manager module, so that using Ansible >= 2.12 on Arch Linux would croak like:
>
>     Unsupported parameters for (ansible.legacy.pacman) module: allow_downgrade.
I feel responsible for that regression, because I just had focussed on Debian and apparently completely missed the big picture. Apologies.
I am submitting this patch to improve the situation as a draft, because I haven't been able to test it hands-on yet. Do you think it would resolve the issue for you? Apparently, as the software tests seem to succeed, can I humbly ask you to give it a try and report back about the outcome?
In order to pull the patched recipe directly …
=> Fix package downgrading for non-{RedHat,Debian} systems

tasks/setup-RedHat.yml
The repo file provided from docker has no spaces before and after the `=` in the ini file. The Ansible task `ini_file` adds spaces before and after the `=` and therefore, even though no change is required since the value is the same, the file is still touch and a change is reported by Ansible.
This fix adds the option `no_extra_spaces: true` option to the two `ini_file` tasks in the RedHat setup tasks.
=> fix: remove extra spaces on enable option in ini files

README.md, defaults/main.yml, handlers/main.yml, tasks/main.yml
On WSL2 (likely also WSL1) this role fails with this error message:
```
TASK [service] ***********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Service is in unknown state", "status": {}}
```
This minimal playbook will fail with the same error:
```yaml
---
- hosts: localhost
tasks:
- service:
name: docker
state: stopped
```
Consequently the `service`  module should not be called by this role in WSL. I added a configuration variable `docker_service_manage` (defaults to `true`) to allow skipping the tasks that call the `service` module.
The README was updated to reflect these changes.
=> Allow skipping of service management

README.md, defaults/main.yml, tasks/main.yml
Fixes #355.
Copied the strategy of the package install for the docker daemon. I left the compose binary enabled as the default, and the compose plugin disabled to avoid breaking any old installs/configs. At some point, though, that should probably be flipped as only the plugin will be supported moving forward.
@geerlingguy please let me know if you'd like any changes.
=> Add installation of docker plugin from docker's repo

handlers/main.yml
Configure module parameters as a YAML dict instead of string.
This PR falls right into the bikeshedding category, but I just had a discussion with a friend about this. We kind of believe that the syntax of configuring a module by a single string is kind of deprecated, at least we thought that we heard it somewhere. I am sadly not able to find a reference for this. But I noticed this is the only place where this is the case.
Personally, while I like compact ways of writing things, I also understand that it is confusing for Ansible beginners to have '=' and ':' mixed… since there is also no strict rules for quoting, they might not realize the 'one is a string, the other a dict' difference. This can be avoided by avoiding the string form.
(PS: Also, it would be kind of nice if the …
=> Avoid string-based module configuration

.github/workflows/ci.yml, README.md, defaults/main.yml, meta/main.yml, tasks/main.yml
Fixes #205.
As [requested here](https://github.com/geerlingguy/ansible-role-docker/issues/205#issuecomment-1068121131) explicitly install all Docker packages and changes the variable(s) name(s).
One note/suggestion: 
You requested to change the name of the variable(s) which makes this a breaking change for the users which configure/override this variable(s). May I ask why? Is it just to be more clear and for naming conventions? Because there is no real need for this. The `package` module supports both strings and lists. 
Keeping it the old way but with a slightly wrong name it would not be a breaking change.
=> #205 - install Docker packages explicitly

tasks/main.yml, vars/Alpine.yml, vars/default.yml
Specific example is Alpine where the [repos](https://pkgs.alpinelinux.org/packages?name=docker&branch=edge) use `docker` rather than `docker-ce` or `docker-ee`
=> Add OS specific variable overrides.

tasks/docker-users.yml, tasks/main.yml
* https://github.com/geerlingguy/ansible-role-docker/issues/237
* https://github.com/geerlingguy/ansible-role-docker/issues/308
Without this modification, we can't use docker in same playbook than the one which install docker (in the case of we use `docker_users` variable).
Check that `docker_users` are set and not in docker group before include `docker-users.yml`. In `docker-users.yml` we call reset_connection` from [ansible.builtin.meta](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/meta_module.html) collection after `docker_users` are added to docker group.
* Try to install docker with only one user in docker-users and not in docker group => docker-users.yml include
* Try to install docker with only one user in docker-users but the user is in docker group => …
=> reset ssh connection to allow user changes to affect current login user

README.md, defaults/main.yml
See #290. Basically make it so the role will work on x86_64 and arm64 out of the box, with no changes required. Can still override the arch for other unique situations.
=> Fixes #290: Allow role to work on ARM64 out of the box.

meta/main.yml, vars/Archlinux.yml
Instead of the current role's default value for `docker_package` (`docker-ce`), the package name for the Archlinux OS distribution is `docker` [1].
Considerations:
* Filename is `Archlinux`, as that is the possible value exposed by Ansible, in `ansible_distribution` [2] and `ansible_os_family` [3].
* Platform name in meta's `galaxy_info` has been changed to `ArchLinux`, as that's the supported platform name in Ansible Galaxy [4].
[1] https://archlinux.org/packages/community/x86_64/docker/
[2] https://docs.ansible.com/ansible/2.6/user_guide/playbooks_conditionals.html#ansible-distribution
[3] https://docs.ansible.com/ansible/2.6/user_guide/playbooks_conditionals.html#ansible-os-family
[4] https://galaxy.ansible.com/api/v1/platforms/?name__icontains=arch
=> Set default docker_package for Archlinux distribution

README.md, defaults/main.yml, tasks/setup-Debian.yml, tasks/setup-RedHat.yml
When using on environments with already pre-configured repositories it is useful to be able to skip tasks configuring a specific docker repository
=> Add flag to deactivate repository configuration

defaults/main.yml, tasks/setup-Debian.yml
As described in https://github.com/ansible/ansible/issues/65687, get_url only partially supports check_mode: "the changed status will reflect comparison to an empty source file".
Before this change, executing this code, with the key already being in place on the target system, would report "OK", while check_mode would report "changed".
Due to this change, both now either report "OK" or "changed", depending on the state of the target system.
=> APT key: don't force and provide checksum, to fix check mode

tasks/setup-RedHat.yml
On RedHat operating systems, runc is provided by default on some installations. This other container implementation conflicts with containerd, making installation impossible without removing it first.
This PR ensures runc is not installed prior to installing containerd so it doesn't fail due to this conflict.
=> remove runc, as it conflicts with containerd

defaults/main.yml
Hi, this is a follow-up PR for #396.
The previous PR fixed `docker_apt_repository` issue by using `docker_apt_ansible_distribution`, but we also needed it in `docker_apt_gpg_key`.
This gpg key needs to be added only once, so I assume the previous environment already had the gpg key for Ubuntu installed in the system.
**Additional info: error logs without this change on the latest role (v7.0.1):**
```shell
(...)
TASK [geerlingguy.docker : Load OS-specific vars.] *****************************
task path: /home/shuuji3/.ansible/roles/geerlingguy.docker/tasks/main.yml:2
ok: [localhost] => {"ansible_facts": {}, "ansible_included_var_files": ["/home/shuuji3/.ansible/roles/geerlingguy.docker/vars/main.yml"], "changed": false}
TASK [geerlingguy.docker : include_tasks] …
```
=> fix: fix failure for the initial gpg key load on Pop!_OS

tasks/setup-Debian.yml
Some packages (e.g amazon-ecr-credential-helper) try to pull docker.io package during installation. If such package is installed during the play before docker role, the docker service will fail to start in a very non-obvious way. 
See [this thread](https://forums.docker.com/t/ubuntu-22-04-and-5-23-0-0-1-now-fails-to-start-please-suggest-debug/134472/11) for more information
=> Uninstall docker.io on apt distros

defaults/main.yml
As of [Docker Engine 23.0](https://docs.docker.com/engine/release-notes/23.0/), `docker-buildx-plugin` is distributed as a separate package, so adding it to the packages list to be installed.
=> Add docker-buildx-plugin to docker_packages

defaults/main.yml
Can install on 32-bit raspbian with same commands, just selecting the right build. https://docs.docker.com/engine/install/raspberry-pi-os/
=> Enable armhf build for old raspberry pis

defaults/main.yml, tasks/setup-Debian.yml
https://github.com/geerlingguy/ansible-role-docker/issues/435
I started this issue because I faced a similar problem as https://github.com/geerlingguy/ansible-role-docker/issues/434
when adding the docker apt repository
`Signed-By regarding source https://download.docker.com/linux/ubuntu/ jammy:
│ /etc/apt/trusted.gpg.d/docker.asc != ,`
Which I then had to fix by:
```
sudo rm /etc/apt/sources.list.d/docker.list
sudo rm /etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list
```
and then running the changes in this branch.
I did some research and noticed that GPG keys should not be placed in `/etc/apt/trusted.gpg.d/` (please see https://github.com/geerlingguy/ansible-role-docker/issues/435)
After updating the tasks to mirror the installation method in …
=> Add GPG keys to `/apt/keyrings` instead of `/apt/trusted.gpg.d`, Update task `Add Docker apt key`

tasks/setup-Debian.yml
See https://github.com/docker/docker-install/pull/391 and https://github.com/docker/docker-install/commit/811f32afe518ae963d13ff92a1bcb0a40c80eb3a.
Also https://wiki.debian.org/DebianRepository/UseThirdParty#OpenPGP_Key_distribution
=> gnupg no longer prerequisite

defaults/main.yml, tasks/setup-Debian.yml
There are some reason (religion, company policy) to force install package from distribution.
We can done that with right parameters (ubuntu 22.04):
- name: Include geerlingguy.docker role
ansible.builtin.include_role:
name: geerlingguy.docker
vars:
docker_add_repo: false
docker_packages:
- docker.io
- containerd
docker_compose_package: docker-compose-v2
docker_obsolete_packages: []
But the role want to remove old versions of Docker, and this remove the distrib packages too.
This patch allow change the list of package to remove.
=> Allow change obsolete packages

README.md
README now shows, that this role is using the recommended docker compose plugin
=> README: Updated docker compose and docker compose plugin default values

tasks/setup-Debian.yml
Fixes https://github.com/geerlingguy/ansible-role-docker/issues/460
https://github.com/geerlingguy/ansible-role-docker/pull/436 introduced a change to the path where the apt key was placed, and to the associated repository listing in `/etc/apt/sources.d/docker.list`. We've just run into a problem with this approach, as detailed in the issue I raised, https://github.com/geerlingguy/ansible-role-docker/issues/460.
So that other people who use the role without pinning a specific version don't run into this same problem, I thought it would be wise to add a couple of tasks which remove any artifacts associated with the previous approach to storing repository keys.
I'm sorry to ping you both, @kawadeomkar / @geerlingguy, but I wonder if you would give this some consideration?
=> Remove trusted.gpg.d artifacts.

README.md, defaults/main.yml
Update the default installed docker-compose version to the latest release v2.29.2
=> Bump docker_compose_version to v2.29.2

tasks/setup-Debian.yml
=> Fix Issue #470

molecule/default/converge.yml, molecule/default/verify.yml
- Add molecule verify playbook
=> feat: Add molecule verify playbook

tasks/setup-Debian.yml
This patch ensures that the correct filename is specified based on the distribution. Observed this behaviour on a Debian system, the old file was not removed due to it being hardcoded to ubuntu instead.
Corrects an issue introduced in #477
=> fix: issue with #470 fix

tasks/setup-Debian.yml
This makes removal succeed when docker_apt_ansible_distribution is
"Ubuntu".
=> fix: lowercase distro name when removing apt source

vars/Alpine.yml
Alpine uses a different package name for `docker compose` than the docker official repo's
This adds an override variable similar to what's already in place for `Archlinux.yml`
=> add compose package to Alpine specific variables

README.md, defaults/main.yml
changes:
- update the `docker_yum_gpg_key` to get the os specific (fedora or centos) yum gpg key in `defaults/main.yml` and `README.md`, if fedora or centos gpg keys are different
=> update: docker_yum_gpg_key variable to get the distro gpg key

tasks/main.yml
If people set options in `docker_daemon_options` (e.g. `{'ipv6': false}`), the role will create the `/etc/docker/daemon.json` file and populate it with the options.
Later on, if people stop setting *all of these* options, the file used to remain in place (containing the old options) and cause trouble. This is unexpected.
If the Docker installation is managed by this role and the `/etc/docker/daemon.json` file is managed by it, it should also take care to:
- either delete the file when it's no longer necessary
- or populate it with empty options if that is what `docker_daemon_options` contains
Deleting the file instead of putting `{}` in it seems like the cleaner approach.
There's a chance that people would like to manage options in `/etc/docker/daemon.json` by themselves (without Ansible) …
=> Ensure the Docker daemon options file (`/etc/docker/daemon.json`) is deleted when no longer needed

handlers/main.yml, tasks/setup-Debian.yml
- Replaces deprecated apt_repository and manual GPG key management with ansible.builtin.deb822_repository, introduced in apt 1.1.
- Updates handlers to use FQCNs.
Should be compatible with all supported Ubuntu and Debian distros. deb822 was introduced in apt 1.1.
=> Refactor Debian setup to use deb822_repository

README.md, defaults/main.yml, molecule/default/converge.yml, molecule/default/molecule.yml, molecule/default/verify.yml, tasks/main.yml, tasks/setup-Debian.yml, tasks/setup-RedHat.yml
Currently, the role failed to run with `INJECT_FACTS_AS_VARS` set to `False` as the required `ansible_*` variables are not defined.
The configuration variable `INJECT_FACTS_AS_VARS` and the Ansible fact namespace `ansible_facts.*` have been added in Ansible 2.5. In the [porting guide of that version](https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.5.html#ansible-fact-namespacing), it stated that:
> A new configuration variable, `inject_facts_as_vars`, has been added to ansible.cfg. Its default setting, 'True', keeps the 2.4 behavior of facts variables being set in the old `ansible_*` locations (while also writing them to the new namespace). This variable is expected to be set to 'False' in a future release. When `inject_facts_as_vars` is set to False, you must refer …
=> Consistently access facts via the ansible_facts.* namespace

meta/main.yml
- Update min Ansible version to 2.15.1 (required for functional deb822 module)
- Adds Debian 13 Trixie as a supported platform
=> Bump min Ansible version and add Debian Trixie platform

README.md, defaults/main.yml, tasks/setup-Debian.yml
* removed unused variables from document
* deb822 repository now correctly uses `docker_apt_filename` as its file name
=> chore: remove unused variables

tasks/setup-Debian.yml
Before the refactor in 7.5.0, the variable `docker_apt_ansible_distribution` was used to construct the URI instead of `ansible_facts.distribution`. I use this role on Debian-based [OSMC](https://osmc.tv/), where the resulting URI is incorrect unless I explicitly override it with that variable. Revert to the previous method of constructing the URI.
=> fix uri in repository file for debian based distributions
